<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>c1f469b5-e6c9-46d4-a4fb-01cd3c3327b7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Musicality.Application\Musicality.Application.csproj" />
    <ProjectReference Include="..\Musicality.Persistence\Musicality.Persistence.csproj" />
    <ProjectReference Include="..\Musicality.Pipelines\Musicality.Pipelines.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="..\Musicality.Pipelines\libs\Eclipse.Core.dll" />
  </ItemGroup>

</Project>
